services:
  - type: web
    name: toolkit-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        sync: false